// Stateful black-box dialog inventory, extended during the same exploration campaign.
// These records are evidence indexes, not assertions of overall saturation.
// A family is exhausted only when pending is empty and its cross-feature checks
// have been recorded. Unsupported dismissal gestures are recorded separately.
export const dialogLedger = [
  { id: 'D01', name: 'Audit details',
    covered: ['populated open', 'View/Hide evidence', 'encrypted reload reconstructs evidence', 'unencrypted summaries withhold detailed evidence', 'report popup content', 'blocked report popup toast', 'history report popup renders', 'model report popup renders', 'X close/reopen', 'Close button', 'focused Close Enter', 'nested override', 'Escape stays open', 'backdrop stays open', 'history detail after current-test delete shows record (conv-1b)'],
    pending: ['empty/legacy detail record: N/A — no legacy schema/migration path exists; fresh, encrypted, unencrypted, and mutated histories all exercised'],
    exits: ['X', 'Close', 'focused Close Enter'], unsupported: ['Escape', 'backdrop'],
  },
  { id: 'D02', name: 'Source intake/review',
    covered: ['URL blank/invalid', 'pasted blank', 'source-type toggle preserves inputs', 'pasted success', 'URL proxy fetch success', 'proxy decline/inferred review', 'malformed assessment fallback', 'irrelevant review/add', 'medium review/add (Add enabled)', 'low review/add (Add enabled)', 'GitHub content fetch → fetched context → save', 'URL explicit title carried to review', 'URL explicit description verified carried to review (source-description-preservation: earlier read excluded textarea)', 'URL review Back preserves URL input', 'title/description editing', 'Back preserves source input', 'input Cancel', 'input X/reopen blank', 'review X/discard/reload', 'input Escape/backdrop stay open', 'review Escape/backdrop stay open', 'held proposal: Cancel disabled, X enabled', 'pending fetch X closes, late response discarded, fresh input blank', 'X followed by late assessment (late-assessment-after-close candidate)', 'IDB save failure → toast, dialog closes, absent after reload → retry success', 'saved source remove/reload', 'source remove+same-title replacement flows into generation analysis (conv-1e)'],
    pending: [],
    exits: ['input Cancel', 'input X', 'review X', 'review Back', 'review Add', 'pending X'], unsupported: ['Escape', 'backdrop', 'pending Cancel (disabled)'],
  },
  { id: 'D03', name: 'Generation wizard',
    covered: ['zero sources disables Next', 'single source selection', 'multiple source run', 'sources Escape/backdrop stay open', 'sources X', 'sources retained across X-reopen', 'options count/batch/tokens/Fast', 'Deep mode gating for profiles', 'count bounds min=1 max=20; 0/999 unclamped in input, clamped at generation', 'options Back preserves source selection and options', 'options X closes to sources view', 'Fast success (profiles skipped; straight to screening)', 'Deep success', 'analysis semantic/auth failure', 'generation semantic/provenance failure', 'Retry', 'error Back→modify→success', 'error X closes failed generation; reopen at sources', 'Advanced profiles edit all fields → generation request', 'provider/model override honored in generation request', 'profile X closes to sources view', 'Screening edit all fields', 'screening Back preserves profiles; Continue regenerates candidates', 'screening X closes to sources view', 'initial generation runs no critique call (refine-only)', 'pending critique-on-refine Back; late response applied to review', 'Add without refining', 'Refine & finish', 'critique failure fallback', 'pending critique X closes; late response discarded', 'generated accept storage failure false success (generated-test-accept-false-success); absent after reload', 'review zero selection submit feedback', 'review selection', 'review refinement 500→retry', 'New run', 'review Escape/backdrop stay open', 'review Cancel', 'Add/reload', 'pending analysis Back', 'pending X retains background generation; reopen completed review', 'count+Deep mode reconstruct across X-reopen (conv-1c)'],
    pending: ['pending refinement X: N/A — refine is synchronous after critique'],
    exits: ['sources Cancel', 'sources X', 'options Back', 'options X', 'running Back', 'running X/background', 'error Back', 'error X', 'profiles Back', 'profile X', 'screening Back', 'screening X', 'review Cancel', 'review X', 'review New run', 'review Add'], unsupported: ['Escape', 'backdrop'],
  },
  { id: 'D04', name: 'Custom test create/edit',
    covered: ['empty name browser validation', 'missing payload validation', 'invalid→correct', 'all fields filled', 'textarea Shift+Enter newline', 'name Enter submits valid form', 'create X discards', 'create Cancel discards', 'create Escape/backdrop stay open', 'create storage failure false success (catalog-create-false-success); absent after reload', 'save→reload→edit', 'edit X discards', 'edit Cancel discards', 'edit blank validation', 'edit Escape/backdrop stay open', 'edit save→reload', 'storage failure false success/reload old state (catalog-edit-false-success)', 'successful retry', 'ATLAS prefilled creation → mapped prompts → reload'],
    pending: [],
    exits: ['create X', 'create Cancel', 'create Save', 'create Enter submit', 'edit X', 'edit Cancel', 'edit Update'], unsupported: ['Escape', 'backdrop', 'async pending (synchronous storage write)'],
  },
  { id: 'D05', name: 'Preset name',
    covered: ['empty OK closes without save', 'Cancel discards', 'Escape/backdrop stay open', 'valid Enter submit', 'storage failure false success (preset-save-false-success); absent after reload', 'save/reload', 'duplicate-name replace confirmation (D23)', 'preset downstream availability after test removal/restore', 'Apply→Runner', 'Runner entry-point save', 'custom preset deletion→reload→Runner absence'],
    pending: [],
    exits: ['Cancel', 'OK', 'Enter'], unsupported: ['X (absent)', 'Escape', 'backdrop', 'async pending (synchronous storage write)'],
  },
  { id: 'D06', name: 'Bulk import',
    covered: ['blank parse', 'malformed parse→correct', 'JSON', 'YAML', 'JSONL', 'CSV', 'native/CSV sample choice and insertion', 'templates collapse/expand', 'mixed valid/missing-payload input', 'Clear/Select all/individual checkbox', 'zero selection submit feedback', 'storage failure false success (bulk-import-false-success); absent after reload', 'oversized input limit message', 'preview Cancel clears draft', 'input X clears draft', 'preview X clears draft', 'input Escape/backdrop stay open', 'preview Escape/backdrop stay open', 'import→reload', 'duplicate import imports twice (no dedupe)', 'bulk textarea Enter inserts newline (no submit)', 'bulk textarea Shift+Enter newline, no submit (conv-1b)'],
    pending: [],
    exits: ['input X', 'preview X', 'preview Cancel', 'Import Selected'], unsupported: ['input Cancel (absent)', 'Escape', 'backdrop', 'file chooser (paste-only UI)'],
  },
  { id: 'D07', name: 'Remove test confirmation',
    covered: ['Cancel retains test', 'Escape/backdrop stay open', 'Confirm via Enter', 'removed reload', 'single remove failure optimistic hide (remove-failure-optimistic-hide); present after reload', 'preset availability drops', 'restore/reload'],
    pending: [],
    exits: ['Cancel', 'Confirm', 'focused Confirm Enter'], unsupported: ['X (absent)', 'Escape', 'backdrop'],
  },
  { id: 'D08', name: 'Runner verdict detail panel',
    covered: ['secure/vulnerable/inconclusive detail', 'X/reopen', 'keyboard Enter opens detail', 'Escape/backdrop stay open', 'nested override', 'original/overridden/cleared', 'historical detail shows original snapshot after current-test edit', 'empty-fault run observed (no inconclusive group; empty path asserted in journeys)', 'technical ERROR detail expands via row click (text click insufficient); shows Model Response + Technical-failure reasoning'],
    pending: [],
    exits: ['X'], unsupported: ['Cancel/Save (absent)', 'Escape', 'backdrop'],
  },
  { id: 'D09', name: 'Override reason',
    covered: ['empty reason Save', 'nonempty multiline reason Save', 'Enter inserts newline (no submit)', 'Cancel discards', 'X discards', 'Escape cancels', 'backdrop stays open', 'reopen original reason', 'reload retains verdict/reason', 'storage failure retains previous verdict and draft→retry', 'Improve disabled with blank reason', 'Improve persists before AI', 'Clear override', 'history/report downstream verified (reason omitted from report)'],
    pending: ['pending save closure: N/A — save is synchronous localStorage (HistoryContext.setResultOverride), no async pending state exists to interleave'],
    exits: ['Cancel', 'X', 'Escape', 'Save Override', 'Improve Judge with AI'], unsupported: ['backdrop'],
  },
  { id: 'D10', name: 'Judge improvement review',
    covered: ['valid rewrite→evaluation and three canaries', 'malformed rewrite→inconclusive previews', 'blank Apply rejected', 'editable proposal', 'Re-run evaluation', 'Re-run canaries', 'fine-tune', 'Cancel', 'X', 'Escape/backdrop stay open', 'pending re-evaluation hides Cancel; X closes; late response discarded', 'refinement 500 boundary-verified + error surfaced + in-review Fine-tune retry', 'Apply prompt', 'Apply and re-evaluate all models', 'override-save fault → review auto-closes', 'forcing feedback flagged', 'stale canary confirmation', 'prompt reload/downstream reevaluation', 'pending canary hold → X → late response discarded (conv-1b)', 'pending rewrite hold observed; no Cancel affordance mid-rewrite; late response discarded via reload (conv-1e)'],
    pending: [],
    exits: ['X', 'Cancel', 'Apply', 'Apply and re-evaluate all models'], unsupported: ['Escape', 'backdrop'],
  },
  { id: 'D11', name: 'Prompt update feedback/review',
    covered: ['empty feedback submit', 'input X/discard', 'input Cancel', 'input Escape/backdrop stay open', 'pending rewrite X→late canary requests', 'missing placeholders rejected in AI rewrite', 'placeholder-dropping rewrite rejected', 'error Back preserves feedback', 'Skip canary preview sends no evaluation calls', 'review Escape/backdrop stay open', 'review Cancel', 'review X closes without applying', 'review editable prompt', 'manual placeholder removal can be applied', 'fine-tune', 'Apply/reload', 'prompt save failure surfaced; review auto-closes', 'source rewrite→later source request', 'all seven customized prompts verified in later AI requests', 'rewrite connection failure → error → Back → retry success (conv-1b)', 'canary 500 → error surfaced; error X closes (conv-1b)', 'Update buttons disabled until Judge helper configured (conv-1b harness learning)'],
    pending: [],
    exits: ['input X', 'input Cancel', 'pending X', 'error X', 'error Back', 'review X', 'review Cancel', 'review Apply'], unsupported: ['Escape', 'backdrop'],
  },
  { id: 'D12', name: 'Unencrypted key warning',
    covered: ['Cancel retains provider draft', 'Escape/backdrop stay open', 'Save anyway', 'Set up encryption→password prompt→provider saved', 'warning-path IDB failure surfaces, draft retained; absent after reload (conv-1a)', 'focused Save-anyway Enter submits (conv-1a)'],
    pending: [],
    exits: ['Cancel', 'Save anyway', 'Set up encryption'], unsupported: ['X (absent)', 'Escape', 'backdrop'],
  },
  { id: 'D13', name: 'Vault unlock',
    covered: ['empty submit', 'wrong passphrase', 'correct unlock', 'Enter submit', 'Escape/backdrop stay open', 'read-only→disabled actions', 'Unlock keys reentry', 'lock/reload', 'passphrase change short-reject + confirm + old-reject + reload + new-unlock + reconstruct', 'pending unlock→read-only→late unlock race (unlock-read-only-race)', 'IDB read-error on unlock surfaces error, stays locked (conv-1a)', 'read-only gates Settings+Runner disabled (conv-1a)', 'correct unlock recovers after fault (conv-1a)', 'wrong passphrase after change stays locked (conv-1c)', 'read-only mutation control hidden in Test Management (conv-1c)'],
    pending: ['direct IDB-blob crypto-corruption: HARNESS-LIMITED — blob surgery races app boot, no stable product signal after 3 attempts; wrong-key rejection covered deterministically'],
    exits: ['Unlock', 'Enter submit', 'Continue in read-only mode'], unsupported: ['X/Cancel (absent)', 'Escape', 'backdrop'],
  },
  { id: 'D14', name: 'Encrypted backup passphrase',
    covered: ['empty validation', 'wrong password→correct retry', 'show/hide password', 'Enter submit', 'Cancel retains welcome/current state', 'Escape/backdrop stay open', 'held decrypt disables Cancel', 'held decrypt release→confirmation', 'corrupted envelope rejected', 'file replacement after cancellation accepted'],
    pending: [], exits: ['Cancel', 'Unlock & import', 'Enter submit'], unsupported: ['X (absent)', 'Escape', 'backdrop', 'pending Cancel (disabled)'],
  },
  { id: 'D15', name: 'Backup import confirmation',
    covered: ['preview counts/names', 'prompt-overrides preview branch; imported prompt wins', 'Cancel leaves existing data', 'Escape/backdrop stay open', 'Confirm→reload/reconstruction', 'IDB failure rolls back entities', 'localStorage failure rolls back; pre-import intact', 'schema-invalid backup rejected', 'double Confirm single import', 'welcome import path', 'settings import path'],
    pending: [],
    exits: ['Cancel', 'Confirm'], unsupported: ['X (absent)', 'Escape', 'backdrop'],
  },
  { id: 'D16', name: 'Proxy consent',
    covered: ['article Cancel→inferred review', 'article Confirm→fetched review', 'blank destination (blank-proxy-destination-consent)', 'provider consent Cancel→Confirm→PUT relay with custom header', 'redirect-follow + relay consent → redirected article assessed', 'Test Proxy success + relay 500 failure', 'consent Escape/backdrop stay open (conv-1a)', 'provider relay gated on provider-category: no consent + direct attempt fails when off (conv-1a)'],
    pending: [],
    exits: ['Cancel', 'Confirm'], unsupported: ['X (absent)'],
  },
  { id: 'D17', name: 'Welcome',
    covered: ['X→reload dismissed', 'Skip→reload dismissed', 'Skip via Enter', 'Escape/backdrop stay open', 'previous export invalid→correct', 'backup cancel returns welcome', 'backup complete reconstructs state', 'start→guided tutorial', 'replay'],
    pending: [],
    exits: ['X', 'Skip', 'focused Skip Enter', 'start tutorial', 'successful previous-export import'], unsupported: ['Escape', 'backdrop'],
  },
  { id: 'D18', name: 'Guided tutorial',
    covered: ['all 19 displayed steps walked 1-18 + Finish', 'Next per step', 'Back returns to step 1 and preserves', 'Escape exits', 'X exits', 'backdrop stays open', 'Skip gated lineup step', 'lineup gate auto-satisfied by 2 preloaded sandbox targets', 'technique-selection gate via Next', 'preset-selection gate via Next and via Skip', 'run gate executes sandbox audit', 'console gate', 'result-detail gate', 'Finish exits tutorial', 'completion persists reload (no auto-restart)', 'keyboard Enter advances tour', 'keyboard Tab+Enter activates Finish (conv-1e)', 'interface-tour reentry', 'fresh-state welcome→start→configuration flow'],
    pending: [],
    exits: ['Escape', 'X', 'Finish'], unsupported: ['backdrop'],
  },
  { id: 'D19', name: 'Provider-triggered encryption passphrase (new)',
    covered: ['short validation retained', 'correct retry', 'Cancel retains draft', 'Escape/backdrop stay open', 'Enter→encrypt and save provider', 'IDB abort → error surfaced + draft retained + absent after reload → retry encrypts'],
    pending: [], exits: ['Cancel', 'OK', 'Enter'], unsupported: ['X (absent)', 'Escape', 'backdrop'],
  },
  { id: 'D20', name: 'Remove vault passphrase confirmation (new)',
    covered: ['Escape/backdrop stay open', 'Cancel keeps encryption', 'Confirm→reload plain vault', 'IDB fault → error surfaced; encrypted persists (conv-1c); one-shot fault race noted: a single non-critical write fault once showed plain vault (harness artifact, two runs two outcomes)'],
    pending: [], exits: ['Cancel', 'Confirm'], unsupported: ['X (absent)', 'Escape', 'backdrop'],
  },
  { id: 'D27', name: 'Provider delete (new: NO confirmation dialog)',
    covered: ['Delete click removes immediately (provider-delete-no-confirmation)', 'removal persists reload'],
    pending: [], exits: ['immediate Delete (no Cancel/Confirm/X/Escape/backdrop exist)'], unsupported: ['Cancel', 'Confirm', 'X', 'Escape', 'backdrop'],
  },
  { id: 'D21', name: 'Stale/forcing Judge proposal confirmation (new)',
    covered: ['stale edited prompt triggers warning', 'Escape/backdrop stay open', 'Cancel returns review', 're-run canaries→normal Apply', 'stale Confirm applies reviewed prompt', 'forcing variant flagged with verdict tokens'],
    pending: [], exits: ['Cancel', 'Confirm'], unsupported: ['X (absent)', 'Escape', 'backdrop'],
  },
  { id: 'D22', name: 'Delete built-in Default preset confirmation (new)',
    covered: ['Escape/backdrop stay open', 'Cancel retains', 'Confirm→reload absent', 'Restore Default preset→reload persists→Runner available', 'delete storage failure retains preset across reload (conv-1b)'],
    pending: [], exits: ['Cancel', 'Confirm'], unsupported: ['X (absent)', 'Escape', 'backdrop'],
  },
  { id: 'D28', name: 'Reset platform confirmation (new)',
    covered: ['Escape stays open', 'backdrop stays open', 'Cancel retains state', 'Confirm returns to welcome', 'reset persists empty state across reload'],
    pending: [], exits: ['Cancel', 'Confirm'], unsupported: ['X (absent)', 'Escape', 'backdrop'],
  },
  { id: 'D23', name: 'Replace duplicate preset confirmation (new)',
    covered: ['duplicate name triggers replace prompt', 'Escape stays open', 'backdrop stays open', 'Cancel retains original single preset', 'Confirm overwrites; survives reload'],
    pending: [], exits: ['Cancel', 'Confirm'], unsupported: ['X (absent)', 'Escape', 'backdrop'],
  },
  { id: 'D24', name: 'Delete audit record confirmation (new)',
    covered: ['Escape stays open', 'backdrop stays open', 'Cancel retains rows', 'Confirm removes row', 'delete persists after reload', 'double Confirm deletes exactly once (conv-1b)'],
    pending: [], exits: ['Cancel', 'Confirm'], unsupported: ['X (absent)', 'Escape', 'backdrop'],
  },
  { id: 'D25', name: 'Clear audit history confirmation (new)',
    covered: ['Escape stays open', 'backdrop stays open', 'Cancel retains history', 'storage failure toast + history retained + reload retained', 'Confirm persists empty history across reload'],
    pending: [], exits: ['Cancel', 'Confirm'], unsupported: ['X (absent)', 'Escape', 'backdrop'],
  },
  { id: 'D26', name: 'Reset test suite confirmation (new)',
    covered: ['Escape stays open', 'backdrop stays open', 'Cancel retains custom test', 'Confirm removes custom tests across reload'],
    pending: [], exits: ['Cancel', 'Confirm'], unsupported: ['X (absent)', 'Escape', 'backdrop'],
  },
];
